### ISSUE TITLE
No User Manual

### ISSUE THREAD

**Issue by j-cse** [AhmedRMunir/PartnerUp#13]
Hello,

The Peer Review asks a lot about a manual to use the software. I did not see one so I read the design doc

**Comment by AhmedRMunir** [comment]
There is a user manual, it is called User-documentation.md

**Comment by j-cse** [comment]
My bad I assumed it was supposed to be apart of the README and didn't see it! Closing issue and making update to Peer Review. Sorry again!

**Comment by j-cse** [comment]
I asked others reviewing and they thought the same thing. I think it might be a good idea to mention the User Manual in the README or link it or something because most people assume README has all of the information about the software and they wouldn't think to look through the files for further documentation.

**Comment by AhmedRMunir** [comment]
Aaaah. Alright, got it! Thanks :D
